
const D=window.INITIAL_DATA, KEY='budget2026.app.v1';
let state=load(), view='home', month=Math.max(0,Math.min(11,new Date().getFullYear()===2026?new Date().getMonth():0)), deferredPrompt=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(D)}catch(e){return structuredClone(D)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function mtx(i){return state.transactions.filter(t=>t.month===i)}
function totals(i){let ts=mtx(i),income=0,expense=0,pincome=0,pexpense=0;for(const t of ts){let rev=t.category.trim()==='Revenus';if(rev){income+=t.amount;if(t.pointed)pincome+=t.amount}else{expense+=t.amount;if(t.pointed)pexpense+=t.amount}}return{income,expense,pincome,pexpense}}
function planned(i){let ls=state.months[i].budgetLines;return{income:ls.filter(x=>x.type==='income').reduce((a,b)=>a+b.planned,0),expense:ls.filter(x=>x.type==='expense').reduce((a,b)=>a+b.planned,0)}}
function balance(i,pointed=true){let prev=i===0?state.months[0].openingBalance:balance(i-1,pointed),t=totals(i);return prev+(pointed?t.pincome:t.income)-(pointed?t.pexpense:t.expense)}
function monthbar(){return `<div class="monthbar">${state.months.map((m,i)=>`<button data-month="${i}" class="${i===month?'active':''}">${m.month}</button>`).join('')}</div>`}
function layout(inner){return `<div class="wrap">${inner}</div>`}
function home(){let t=totals(month),p=planned(month),b=balance(month,true),delta=(t.pincome-t.pexpense)-(p.income-p.expense);let cat={};for(const x of mtx(month).filter(x=>x.category.trim()!=='Revenus'&&x.pointed))cat[x.category]=(cat[x.category]||0)+x.amount;let cats=Object.entries(cat).sort((a,b)=>b[1]-a[1]).slice(0,6);return layout(`${monthbar()}<section class="hero"><div class="label">Solde pointé • ${state.months[month].month}</div><div class="big">${euro(b)}</div><div class="hero-grid"><div class="hero-mini">Revenus pointés<b>${euro(t.pincome)}</b></div><div class="hero-mini">Dépenses pointées<b>${euro(t.pexpense)}</b></div><div class="hero-mini">Budget prévu<b>${euro(p.expense)}</b></div><div class="hero-mini">Reste budget<b>${euro(p.expense-t.expense)}</b></div></div></section><div class="cards"><div class="card"><div class="cap">REVENUS RÉELS</div><div class="val positive">${euro(t.income)}</div></div><div class="card"><div class="cap">DÉPENSES RÉELLES</div><div class="val negative">${euro(t.expense)}</div></div><div class="card"><div class="cap">SOLDE RÉEL</div><div class="val ${balance(month,false)>=0?'positive':'negative'}">${euro(balance(month,false))}</div></div><div class="card"><div class="cap">ÉCART VS PRÉVU</div><div class="val ${delta>=0?'positive':'negative'}">${euro(delta)}</div></div></div><div class="section-title"><h2>Dépenses par catégorie</h2><button class="btn secondary" data-go="budget">Budget</button></div><div class="list">${cats.length?cats.map(([c,v])=>`<div class="row"><div><div class="title">${esc(c)}</div><div class="progress"><i style="width:${Math.min(100,v/(t.pexpense||1)*100)}%"></i></div></div><div class="amount">${euro(v)}</div></div>`).join(''):'<div class="empty">Aucune dépense pointée.</div>'}</div><div class="section-title"><h2>Derniers mouvements</h2><button class="btn secondary" data-go="transactions">Tout voir</button></div>${txList(mtx(month).slice(-6).reverse())}<button class="fab" data-add>+</button>`) }
function txList(list){return `<div class="list">${list.length?list.map(t=>`<div class="row" data-edit="${esc(t.id)}"><div><div class="title">${t.pointed?'✓ ':''}${esc(t.description||t.subcategory||'Mouvement')}</div><div class="sub">${t.day?String(t.day).padStart(2,'0')+'/':''}${String(t.month+1).padStart(2,'0')}/2026 · ${esc(t.category)}${t.subcategory?' › '+esc(t.subcategory):''}</div></div><div class="amount ${t.category.trim()==='Revenus'?'positive':'negative'}">${t.category.trim()==='Revenus'?'+':'−'}${euro(Math.abs(t.amount))}</div></div>`).join(''):'<div class="empty">Aucun mouvement.</div>'}</div>`}
function txGroups(list){
  const billCats=new Set(['Habitation','Télécommunications','Assurances','Banque','Impots']);
  const revenus=list.filter(t=>t.category.trim()==='Revenus');
  const factures=list.filter(t=>t.category.trim()!=='Revenus'&&billCats.has(t.category.trim()));
  const autres=list.filter(t=>t.category.trim()!=='Revenus'&&!billCats.has(t.category.trim()));
  const total=a=>a.reduce((s,t)=>s+(Number(t.amount)||0),0);
  return `
    <section class="txgroup income-group">
      <div class="txgroup-head"><div><span class="txgroup-icon">↗</span><h3>Revenus</h3><small>${revenus.length} mouvement${revenus.length>1?'s':''}</small></div><strong class="positive">+${euro(total(revenus))}</strong></div>
      ${txList(revenus)}
    </section>
    <section class="txgroup bills-group">
      <div class="txgroup-head"><div><span class="txgroup-icon">▣</span><h3>Factures</h3><small>${factures.length} mouvement${factures.length>1?'s':''}</small></div><strong class="negative">−${euro(total(factures))}</strong></div>
      ${txList(factures)}
    </section>
    <section class="txgroup other-group">
      <div class="txgroup-head"><div><span class="txgroup-icon">•••</span><h3>Autres dépenses</h3><small>${autres.length} mouvement${autres.length>1?'s':''}</small></div><strong class="negative">−${euro(total(autres))}</strong></div>
      ${txList(autres)}
    </section>`;
}
function transactions(){let list=mtx(month).slice().sort((a,b)=>(b.day||0)-(a.day||0));return layout(`${monthbar()}<div class="section-title"><h2>Mouvements • ${state.months[month].month}</h2><button class="btn" data-add>+ Ajouter</button></div><input class="search" id="search" placeholder="Rechercher dans les mouvements…"> <div id="txarea" style="margin-top:12px">${txGroups(list)}</div>`)}
function budget(){let ls=state.months[month].budgetLines, groups={};for(const l of ls)(groups[l.type==='income'?'Revenus':l.category]??=[]).push(l);return layout(`${monthbar()}<div class="section-title"><h2>Budget prévu • ${state.months[month].month}</h2><button class="btn secondary" data-go="home">Terminé</button></div><div class="list">${Object.entries(groups).map(([g,ls])=>`<div class="cathead">${esc(g)}</div>${ls.map((l,idx)=>{let gi=state.months[month].budgetLines.indexOf(l);let actual=mtx(month).filter(t=>l.type==='income'?t.category.trim()==='Revenus':t.category.trim()===g.trim()).reduce((a,b)=>a+b.amount,0);return `<div class="budgetrow"><div><b>${esc(l.label)}</b><small>${l.type==='income'?'Revenu':'Dépense'}</small></div><input type="number" step="0.01" value="${l.planned}" data-budget="${gi}"><div class="actual">${euro(actual)}</div></div>`}).join('')}`).join('')}</div><p class="muted">Colonne centrale : montant anticipé modifiable. À droite : réel actuel de la catégorie.</p>`)}
function annual(){let arr=state.months.map((m,i)=>{let t=totals(i),p=planned(i);return{m:m.month.slice(0,3),inc:t.income,exp:t.expense,planned:p.expense,bal:t.income-t.expense}});let inc=arr.reduce((a,b)=>a+b.inc,0),exp=arr.reduce((a,b)=>a+b.exp,0),bud=arr.reduce((a,b)=>a+b.planned,0),mx=Math.max(...arr.map(x=>Math.abs(x.bal)),1);return layout(`<div class="section-title"><h2>Synthèse annuelle 2026</h2></div><div class="kpi3"><div class="card"><div class="cap">REVENUS</div><div class="val positive">${euro(inc)}</div></div><div class="card"><div class="cap">DÉPENSES</div><div class="val negative">${euro(exp)}</div></div><div class="card"><div class="cap">SOLDE</div><div class="val ${inc-exp>=0?'positive':'negative'}">${euro(inc-exp)}</div></div></div><div class="card" style="margin-top:12px"><div class="cap">SOLDE MENSUEL</div><div class="chart">${arr.map(x=>`<div class="barcol"><div class="bar ${x.bal<0?'neg':''}" style="height:${Math.max(3,Math.abs(x.bal)/mx*130)}px"></div><span>${x.m}</span></div>`).join('')}</div></div><div class="section-title"><h2>Mois par mois</h2></div><div class="list">${arr.map((x,i)=>`<div class="row" data-monthgo="${i}"><div><div class="title">${state.months[i].month}</div><div class="sub">Budget dépenses ${euro(x.planned)} · Réel ${euro(x.exp)}</div></div><div class="amount ${x.bal>=0?'positive':'negative'}">${euro(x.bal)}</div></div>`).join('')}</div>`)}
function savings(){
  const rows=(window.KERBUDGET_EXCEL_EXTRA?.Epargne||[]);
  const data=rows.slice(4).filter(r=>r && r[1]);
  const opening=data.find(r=>String(r[1]).toLowerCase().includes('solde précédent'));
  const months=data.filter(r=>/janvier|février|fevrier|mars|avril|mai|juin|juillet|aout|août|septembre|octobre|novembre|décembre|decembre/i.test(String(r[1])));
  const total=data.find(r=>String(r[1]).toLowerCase()==='total');
  const pointed=total ? Number(total[5]||0) : 0;
  const real=total ? Number(total[3]||0) : 0;
  const planned=total ? Number(total[2]||0) : 0;
  return layout(`
    <section class="hero">
      <div class="label">Épargne • Livret A</div>
      <div class="big">${euro(pointed)}</div>
      <div class="hero-grid">
        <div class="hero-mini">Solde précédent<b>${euro(opening?.[5] ?? opening?.[3] ?? 0)}</b></div>
        <div class="hero-mini">Objectif annuel<b>${euro(planned)}</b></div>
        <div class="hero-mini">Réel annuel<b>${euro(real)}</b></div>
        <div class="hero-mini">Pointé<b>${euro(pointed)}</b></div>
      </div>
    </section>
    <div class="section-title"><h2>Épargne mois par mois</h2></div>
    <div class="list">
      ${months.map(r=>`
        <div class="row">
          <div>
            <div class="title">${esc(r[1])}</div>
            <div class="sub">Prévu ${euro(r[2])} · Réel ${euro(r[3])} · Écart ${euro(r[4])}</div>
          </div>
          <div class="amount ${Number(r[5]||0)>=0?'positive':'negative'}">${euro(r[5])}</div>
        </div>`).join('')}
    </div>
  `)
}
function solar(){let paid=state.transactions.filter(t=>/sygma/i.test(t.subcategory)||/sygma/i.test(t.description)).filter(t=>t.pointed).reduce((a,b)=>a+b.amount,0),start=13819.47,remain=Math.max(0,start-paid);return layout(`<div class="hero"><div class="label">Prêt photovoltaïque</div><div class="big">${euro(remain)}</div><div class="hero-grid"><div class="hero-mini">Montant initial<b>${euro(start)}</b></div><div class="hero-mini">Payé / pointé<b>${euro(paid)}</b></div></div></div><div class="section-title"><h2>Échéancier</h2></div><div class="list">${state.solar.map(x=>`<div class="row"><div><div class="title">Échéance ${x.n} · ${esc(x.month)}</div><div class="sub">Montant prévu</div></div><div class="amount">${euro(x.scheduled)}</div></div>`).join('')}</div>`)}
function more(){return layout(`<div class="section-title"><h2>Outils</h2></div><div class="list"><div class="row" data-go="solar"><div><div class="title">☀ Prêt photovoltaïque</div><div class="sub">Échéancier et reste dû</div></div><b>›</b></div><div class="row" data-export><div><div class="title">⇩ Sauvegarder les données</div><div class="sub">Export JSON de l'application</div></div><b>›</b></div><div class="row" data-import><div><div class="title">⇧ Restaurer une sauvegarde</div><div class="sub">Importer un fichier JSON</div></div><b>›</b></div><div class="row" data-reset><div><div class="title negative">Réinitialiser depuis Excel</div><div class="sub">Remet les données intégrées à l'origine</div></div><b>›</b></div></div><input id="fileInput" type="file" accept="application/json" hidden><p class="muted">Les données sont enregistrées automatiquement sur cet appareil, même hors connexion.</p>`)}
function render(){let html=view==='home'?home():view==='transactions'?transactions():view==='annual'?annual():view==='savings'?savings():view==='budget'?budget():view==='solar'?solar():more();document.querySelector('#app').innerHTML=html;document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bind()}
function bind(){document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month=+b.dataset.month;render()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render()});document.querySelectorAll('[data-monthgo]').forEach(b=>b.onclick=()=>{month=+b.dataset.monthgo;view='home';render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>editTx());document.querySelectorAll('[data-edit]').forEach(r=>r.onclick=()=>editTx(r.dataset.edit));document.querySelectorAll('[data-budget]').forEach(i=>i.onchange=()=>{state.months[month].budgetLines[+i.dataset.budget].planned=+i.value||0;save()});let q=document.querySelector('#search');if(q)q.oninput=()=>{let s=q.value.toLowerCase(),l=mtx(month).filter(t=>(t.description+' '+t.category+' '+t.subcategory).toLowerCase().includes(s));document.querySelector('#txarea').innerHTML=txGroups(l);document.querySelectorAll('[data-edit]').forEach(r=>r.onclick=()=>editTx(r.dataset.edit))};let ex=document.querySelector('[data-export]');if(ex)ex.onclick=exportData;let im=document.querySelector('[data-import]');if(im)im.onclick=()=>document.querySelector('#fileInput').click();let fi=document.querySelector('#fileInput');if(fi)fi.onchange=importData;let rs=document.querySelector('[data-reset]');if(rs)rs.onclick=()=>{if(confirm('Revenir aux données d’origine importées depuis Excel ?')){state=structuredClone(D);save();render()}}}
function editTx(id){let old=id?state.transactions.find(t=>t.id===id):null,t=old||{id:'u'+Date.now(),month,day:new Date().getDate(),description:'',amount:0,category:'Dépenses',subcategory:'',pointed:false};let cats=Object.keys(state.categories);document.querySelector('#modal').hidden=false;document.querySelector('#modal').innerHTML=`<div class="sheet"><h2>${old?'Modifier':'Nouveau'} mouvement</h2><div class="field"><label>Jour</label><input id="fday" type="number" min="1" max="31" value="${t.day||''}"></div><div class="field"><label>Désignation</label><input id="fdesc" value="${esc(t.description)}"></div><div class="field"><label>Montant (€)</label><input id="famount" type="number" step="0.01" value="${t.amount}"></div><div class="field"><label>Catégorie</label><select id="fcat">${cats.map(c=>`<option ${c===t.category?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="field"><label>Sous-catégorie</label><select id="fsub"></select></div><label class="check"><input id="fpoint" type="checkbox" ${t.pointed?'checked':''}> Opération pointée</label><div class="actions">${old?'<button class="btn danger" id="del">Supprimer</button>':''}<button class="btn secondary" id="cancel">Annuler</button><button class="btn" id="ok">Enregistrer</button></div></div>`;let cat=document.querySelector('#fcat'),sub=document.querySelector('#fsub');function subs(){let list=state.categories[cat.value]||[];sub.innerHTML='<option value="">—</option>'+list.map(x=>`<option ${x===t.subcategory?'selected':''}>${esc(x)}</option>`).join('')}cat.onchange=subs;subs();document.querySelector('#cancel').onclick=closeModal;document.querySelector('#ok').onclick=()=>{t.month=month;t.day=+document.querySelector('#fday').value||null;t.description=document.querySelector('#fdesc').value.trim();t.amount=+document.querySelector('#famount').value||0;t.category=cat.value;t.subcategory=sub.value;t.pointed=document.querySelector('#fpoint').checked;if(!old)state.transactions.push(t);save();closeModal();render()};let del=document.querySelector('#del');if(del)del.onclick=()=>{if(confirm('Supprimer ce mouvement ?')){state.transactions=state.transactions.filter(x=>x.id!==t.id);save();closeModal();render()}}}
function closeModal(){document.querySelector('#modal').hidden=true;document.querySelector('#modal').innerHTML=''}
function exportData(){let b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='budget-2026-sauvegarde.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();alert('Sauvegarde restaurée.');render()}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f)}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;let b=document.querySelector('#installBtn');b.hidden=false;b.onclick=()=>deferredPrompt.prompt()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
